---
generate_lesson_content_task:
  description: Create lesson number {lesson_number} on the topic {current_topic} for a
    course on {course_topic}. First, list '10 things I need to know about
    {current_topic} in {course_topic}'. Then, for each topic, Add a two to five paragraph
    description, use examples wherever necessary. Finally, propose three follow up topics.
  expected_output: A lesson formatted as markdown.
  async_execution: false
  agent: teacher_content_specialist
simulate_student_qa_task:
  description: Simulate a classroom Q&A session for lesson {lesson_number} under the
    current topic {current_topic}. First, list five students from diverse backgrounds.
    Then, generate a unique question from each student related to the lesson content.
  expected_output: A list of 5 students and their questions.
  async_execution: false
  agent: student_interaction_specialist
  context:
  - generate_lesson_content_task
process_voting_and_filter_task:
  description: Simulate voting on the student questions. Based on the questions asked by
    the students, propose a few topics for the next lesson. Filter out any questions that
    have been discussed in previous lessons to ensure only fresh questions remain. Each
    student will vote on a three questions and give a reason why they chose it. Then,
    rank the questions by decreasing vote counts. Finally, declare the winner.
  expected_output: Possible topics for next lesson, voting with justification, tally, and
    the winner.
  async_execution: false
  agent: discussion_moderator_expert
  context:
  - simulate_student_qa_task
  - generate_lesson_content_task
